// Single source of truth: tokens/*.json (DTCG format).
// Outputs CSS variables, a Tailwind preset (web + NativeWind) and a React Native theme.
import StyleDictionary from 'style-dictionary';

const PREFIX = 'ag';

const hexToChannels = (hex) => {
  const h = hex.replace('#', '');
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).join(' ');
};
const dark = (t) => t.$extensions?.agarha?.dark ?? t.original?.$extensions?.agarha?.dark;
const cssName = (t) => `--${PREFIX}-${t.path.join('-')}`;
const byGroup = (tokens, group) => tokens.filter((t) => t.path[0] === group);

/** Maps token paths to short Tailwind colour keys, e.g. color.brand.primary -> brand.DEFAULT */
const TAILWIND_COLOR_KEYS = {
  'brand.primary': ['brand', 'DEFAULT'],
  'brand.pressed': ['brand', 'pressed'],
  'brand.subtle': ['brand', 'subtle'],
  'accent.featured': ['featured', 'DEFAULT'],
  'accent.on-featured': ['featured', 'fg'],
  'text.primary': ['fg', 'DEFAULT'],
  'text.secondary': ['fg', 'secondary'],
  'border.default': ['border', 'DEFAULT'],
  'surface.page': ['page', 'DEFAULT'],
  'surface.card': ['card', 'DEFAULT'],
  'status.available': ['available', 'DEFAULT'],
  'status.stale': ['stale', 'DEFAULT'],
  'status.danger': ['danger', 'DEFAULT'],
  'status.info': ['info', 'DEFAULT'],
};

function colorVars(tokens, mode) {
  return byGroup(tokens, 'color')
    .map((t) => `  ${cssName(t)}: ${hexToChannels(mode === 'dark' ? dark(t) : t.$value)};`)
    .join('\n');
}

StyleDictionary.registerFormat({
  name: 'agarha/css',
  format: ({ dictionary }) => {
    const all = dictionary.allTokens;
    const px = (g) => byGroup(all, g).map((t) => `  ${cssName(t)}: ${t.$value}px;`).join('\n');
    const motion = byGroup(all, 'motion')
      .map((t) =>
        t.path[1] === 'duration'
          ? `  ${cssName(t)}: ${t.$value}ms;`
          : `  ${cssName(t)}: cubic-bezier(${t.$value.join(', ')});`,
      )
      .join('\n');
    const z = byGroup(all, 'z').map((t) => `  ${cssName(t)}: ${t.$value};`).join('\n');
    const shadows = byGroup(all, 'elevation').map((t) => `  ${cssName(t)}: ${t.$value};`).join('\n');
    const families = all
      .filter((t) => t.path[0] === 'font' && t.path[1] === 'family')
      .map((t) => `  ${cssName(t)}: ${t.$value.map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`)
      .join('\n');
    const body = all.find((t) => t.path.join('.') === 'font.scale.body');
    const arLeading = body.$extensions?.agarha?.arLineHeight ?? body.original.$extensions.agarha.arLineHeight;
    return `/* Generated by @agarha/tokens. Do not edit. Colours are "R G B" channels for alpha support. */
:root {
${colorVars(all, 'light')}
${px('space')}
${px('radius')}
${shadows}
${motion}
${z}
${families}
  --${PREFIX}-font-ui: var(--${PREFIX}-font-family-ui-ar);
  --${PREFIX}-leading-body: 24px;
  color-scheme: light;
}
:root:lang(en) { --${PREFIX}-font-ui: var(--${PREFIX}-font-family-ui-en); }
:root:lang(ar) { --${PREFIX}-leading-body: ${arLeading}px; }
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${colorVars(all, 'dark').replace(/^/gm, '  ')}
    color-scheme: dark;
  }
}
:root[data-theme='dark'] {
${colorVars(all, 'dark')}
  color-scheme: dark;
}
@media (prefers-reduced-motion: reduce) {
  :root {
    --${PREFIX}-motion-duration-fast: 0ms;
    --${PREFIX}-motion-duration-base: 0ms;
    --${PREFIX}-motion-duration-slow: 0ms;
  }
}
`;
  },
});

// NativeWind v4 reads CSS variables from its global.css; it uses `.dark:root` for dark mode.
StyleDictionary.registerFormat({
  name: 'agarha/css-native',
  format: ({ dictionary }) => `/* Generated by @agarha/tokens for NativeWind. Do not edit. */
:root {
${colorVars(dictionary.allTokens, 'light')}
}
.dark:root {
${colorVars(dictionary.allTokens, 'dark')}
}
`,
});

function tailwindPreset(all) {
  const colors = {};
  for (const t of byGroup(all, 'color')) {
    const key = TAILWIND_COLOR_KEYS[t.path.slice(1).join('.')];
    if (!key) throw new Error(`No Tailwind key for ${t.path.join('.')}`);
    colors[key[0]] ??= {};
    colors[key[0]][key[1]] = `rgb(var(${cssName(t)}) / <alpha-value>)`;
  }
  const map = (g, fn) => Object.fromEntries(byGroup(all, g).map((t) => [t.path.at(-1), fn(t)]));
  const fontSize = {};
  for (const t of all.filter((t) => t.path[1] === 'scale')) {
    const v = t.$value;
    const opts = { lineHeight: t.path[2] === 'body' ? `var(--${PREFIX}-leading-body)` : `${v.lineHeight / 16}rem`, fontWeight: String(v.fontWeight) };
    if (v.letterSpacing) opts.letterSpacing = v.letterSpacing;
    fontSize[t.path[2]] = [`${v.fontSize / 16}rem`, opts];
  }
  const duration = Object.fromEntries(
    all.filter((t) => t.path[1] === 'duration').map((t) => [t.path[2], `${t.$value}ms`]),
  );
  return {
    theme: {
      screens: map('breakpoint', (t) => `${t.$value}px`),
      extend: {
        colors,
        spacing: map('space', (t) => `${t.$value / 16}rem`),
        borderRadius: map('radius', (t) => (t.path.at(-1) === 'full' ? '9999px' : `${t.$value / 16}rem`)),
        boxShadow: map('elevation', (t) => t.$value),
        fontSize,
        fontFamily: {
          ui: [`var(--${PREFIX}-font-ui)`],
          display: all.find((t) => t.path.join('.') === 'font.family.display').$value,
        },
        transitionDuration: duration,
        transitionTimingFunction: { out: 'cubic-bezier(0, 0, 0.2, 1)' },
        zIndex: map('z', (t) => String(t.$value)),
        minHeight: { touch: '48px' },
        minWidth: { touch: '48px' },
      },
    },
  };
}

StyleDictionary.registerFormat({
  name: 'agarha/tailwind-preset',
  format: ({ dictionary }) =>
    `// Generated by @agarha/tokens. Do not edit.\n/** @type {import('tailwindcss').Config} */\nmodule.exports = ${JSON.stringify(tailwindPreset(dictionary.allTokens), null, 2)};\n`,
});

function nativeTheme(all) {
  const colors = { light: {}, dark: {} };
  for (const t of byGroup(all, 'color')) {
    const key = t.path.slice(1).join('-').replace(/-(\w)/g, (_, c) => c.toUpperCase());
    colors.light[key] = t.$value;
    colors.dark[key] = dark(t);
  }
  const map = (g) => Object.fromEntries(byGroup(all, g).map((t) => [t.path.at(-1), t.$value]));
  const type = Object.fromEntries(
    all.filter((t) => t.path[1] === 'scale').map((t) => {
      const { textTransform: _t, fontVariantNumeric, ...v } = t.$value;
      const out = { ...v, fontWeight: String(v.fontWeight) };
      if (fontVariantNumeric) out.fontVariant = [fontVariantNumeric];
      if (v.letterSpacing) out.letterSpacing = parseFloat(v.letterSpacing) * v.fontSize;
      if (t.path[2] === 'body') out.lineHeightAr = t.$extensions?.agarha?.arLineHeight ?? t.original.$extensions.agarha.arLineHeight;
      return [t.path[2], out];
    }),
  );
  return {
    colors,
    space: map('space'),
    radius: map('radius'),
    zIndex: map('z'),
    duration: Object.fromEntries(all.filter((t) => t.path[1] === 'duration').map((t) => [t.path[2], t.$value])),
    type,
    fontFamily: { uiAr: 'IBMPlexSansArabic', uiEn: 'IBMPlexSans', display: 'Rubik' },
    iconStroke: all.find((t) => t.path.join('.') === 'icon.stroke').$value,
    touchTarget: { ios: 44, android: 48 },
  };
}

StyleDictionary.registerFormat({
  name: 'agarha/native-theme',
  format: ({ dictionary }) =>
    `// Generated by @agarha/tokens. Do not edit.\n'use strict';\nconst theme = ${JSON.stringify(nativeTheme(dictionary.allTokens), null, 2)};\nmodule.exports = { theme };\n`,
});

const sd = new StyleDictionary({
  source: ['tokens/**/*.json'],
  usesDtcg: true,
  log: { verbosity: 'default' },
  platforms: {
    all: {
      transforms: ['name/kebab'],
      buildPath: 'build/',
      files: [
        { destination: 'css/tokens.css', format: 'agarha/css' },
        { destination: 'css/tokens.native.css', format: 'agarha/css-native' },
        { destination: 'tailwind-preset.js', format: 'agarha/tailwind-preset' },
        { destination: 'native/theme.js', format: 'agarha/native-theme' },
        { destination: 'tokens.json', format: 'json/nested' },
      ],
    },
  },
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
